### ISSUE TITLE
Update Axios dependency

### ISSUE THREAD

**Issue by kentico-michaelb** [Kentico/kontent-core-js#22]
### Brief bug description

There were security issues found within 0.21.1 and 0.21.2 versions of Axios. The Kontent Core package should be updated to the latest version of Axios, and all dependent packages should update to the latest version of Kontent Core.

**Comment by Enngage** [comment]
Fixes by https://github.com/Kentico/kontent-core-js/commit/c42b40a346f832e89acdfa1b9f5d91b5482ea116 and released in `9.2.0`
